package com.example.hibernate;
// Generated Feb 23, 2020, 8:51:51 PM by Hibernate Tools 5.4.7.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private int accountId;
	private User user;
	private String accountType;
	private BigDecimal currentAmount;
	private Date createdDate;
	private Integer status;
	private Set transactionsForFromAccount = new HashSet(0);
	private Set transactionsForToAccount = new HashSet(0);

	public Account() {
	}

	public Account(int accountId) {
		this.accountId = accountId;
	}

	public Account(int accountId, User user, String accountType, BigDecimal currentAmount, Date createdDate,
			Integer status, Set transactionsForFromAccount, Set transactionsForToAccount) {
		this.accountId = accountId;
		this.user = user;
		this.accountType = accountType;
		this.currentAmount = currentAmount;
		this.createdDate = createdDate;
		this.status = status;
		this.transactionsForFromAccount = transactionsForFromAccount;
		this.transactionsForToAccount = transactionsForToAccount;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public BigDecimal getCurrentAmount() {
		return this.currentAmount;
	}

	public void setCurrentAmount(BigDecimal currentAmount) {
		this.currentAmount = currentAmount;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Set getTransactionsForFromAccount() {
		return this.transactionsForFromAccount;
	}

	public void setTransactionsForFromAccount(Set transactionsForFromAccount) {
		this.transactionsForFromAccount = transactionsForFromAccount;
	}

	public Set getTransactionsForToAccount() {
		return this.transactionsForToAccount;
	}

	public void setTransactionsForToAccount(Set transactionsForToAccount) {
		this.transactionsForToAccount = transactionsForToAccount;
	}

}
