package com.example.hibernate;
// Generated Feb 23, 2020, 8:51:51 PM by Hibernate Tools 5.4.7.Final

/**
 * Request generated by hbm2java
 */
public class Request implements java.io.Serializable {

	private int requestId;
	private User userByRequestAssignedTo;
	private User userByRequestedBy;
	private Integer typeOfRequest;
	private String typeOfAccount;

	public Request() {
	}

	public Request(int requestId) {
		this.requestId = requestId;
	}

	public Request(int requestId, User userByRequestAssignedTo, User userByRequestedBy, Integer typeOfRequest,
			String typeOfAccount) {
		this.requestId = requestId;
		this.userByRequestAssignedTo = userByRequestAssignedTo;
		this.userByRequestedBy = userByRequestedBy;
		this.typeOfRequest = typeOfRequest;
		this.typeOfAccount = typeOfAccount;
	}

	public int getRequestId() {
		return this.requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	public User getUserByRequestAssignedTo() {
		return this.userByRequestAssignedTo;
	}

	public void setUserByRequestAssignedTo(User userByRequestAssignedTo) {
		this.userByRequestAssignedTo = userByRequestAssignedTo;
	}

	public User getUserByRequestedBy() {
		return this.userByRequestedBy;
	}

	public void setUserByRequestedBy(User userByRequestedBy) {
		this.userByRequestedBy = userByRequestedBy;
	}

	public Integer getTypeOfRequest() {
		return this.typeOfRequest;
	}

	public void setTypeOfRequest(Integer typeOfRequest) {
		this.typeOfRequest = typeOfRequest;
	}

	public String getTypeOfAccount() {
		return this.typeOfAccount;
	}

	public void setTypeOfAccount(String typeOfAccount) {
		this.typeOfAccount = typeOfAccount;
	}

}
