package com.example.hibernate;
// Generated Feb 23, 2020, 8:51:51 PM by Hibernate Tools 5.4.7.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

	private int transactionId;
	private Account accountByFromAccount;
	private Account accountByToAccount;
	private User user;
	private Integer transactionType;
	private Integer transactionStatus;
	private BigDecimal transactionAmount;
	private Boolean isCriticalTransaction;
	private Date transactionCreatedDate;
	private Date transactionUpdatedDate;

	public Transaction() {
	}

	public Transaction(int transactionId) {
		this.transactionId = transactionId;
	}

	public Transaction(int transactionId, Account accountByFromAccount, Account accountByToAccount, User user,
			Integer transactionType, Integer transactionStatus, BigDecimal transactionAmount,
			Boolean isCriticalTransaction, Date transactionCreatedDate, Date transactionUpdatedDate) {
		this.transactionId = transactionId;
		this.accountByFromAccount = accountByFromAccount;
		this.accountByToAccount = accountByToAccount;
		this.user = user;
		this.transactionType = transactionType;
		this.transactionStatus = transactionStatus;
		this.transactionAmount = transactionAmount;
		this.isCriticalTransaction = isCriticalTransaction;
		this.transactionCreatedDate = transactionCreatedDate;
		this.transactionUpdatedDate = transactionUpdatedDate;
	}

	public int getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	public Account getAccountByFromAccount() {
		return this.accountByFromAccount;
	}

	public void setAccountByFromAccount(Account accountByFromAccount) {
		this.accountByFromAccount = accountByFromAccount;
	}

	public Account getAccountByToAccount() {
		return this.accountByToAccount;
	}

	public void setAccountByToAccount(Account accountByToAccount) {
		this.accountByToAccount = accountByToAccount;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(Integer transactionType) {
		this.transactionType = transactionType;
	}

	public Integer getTransactionStatus() {
		return this.transactionStatus;
	}

	public void setTransactionStatus(Integer transactionStatus) {
		this.transactionStatus = transactionStatus;
	}

	public BigDecimal getTransactionAmount() {
		return this.transactionAmount;
	}

	public void setTransactionAmount(BigDecimal transactionAmount) {
		this.transactionAmount = transactionAmount;
	}

	public Boolean getIsCriticalTransaction() {
		return this.isCriticalTransaction;
	}

	public void setIsCriticalTransaction(Boolean isCriticalTransaction) {
		this.isCriticalTransaction = isCriticalTransaction;
	}

	public Date getTransactionCreatedDate() {
		return this.transactionCreatedDate;
	}

	public void setTransactionCreatedDate(Date transactionCreatedDate) {
		this.transactionCreatedDate = transactionCreatedDate;
	}

	public Date getTransactionUpdatedDate() {
		return this.transactionUpdatedDate;
	}

	public void setTransactionUpdatedDate(Date transactionUpdatedDate) {
		this.transactionUpdatedDate = transactionUpdatedDate;
	}

}
