package com.example.hibernate;
// Generated Mar 13, 2020, 2:30:54 PM by Hibernate Tools 5.4.7.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private Integer accountId;
	private User userByUserId;
	private User userByApprover;
	private String accountNumber;
	private String accountType;
	private BigDecimal currentBalance;
	private Date createdDate;
	private boolean approvalStatus;
	private BigDecimal interest;
	private Date approvalDate;
	private Set transactionsForFromAccount = new HashSet(0);
	private Set transactionsForToAccount = new HashSet(0);

	public Account() {
	}

	public Account(User userByUserId, String accountNumber, String accountType, Date createdDate,
			boolean approvalStatus) {
		this.userByUserId = userByUserId;
		this.accountNumber = accountNumber;
		this.accountType = accountType;
		this.createdDate = createdDate;
		this.approvalStatus = approvalStatus;
	}

	public Account(User userByUserId, User userByApprover, String accountNumber, String accountType,
			BigDecimal currentBalance, Date createdDate, boolean approvalStatus, BigDecimal interest, Date approvalDate,
			Set transactionsForFromAccount, Set transactionsForToAccount) {
		this.userByUserId = userByUserId;
		this.userByApprover = userByApprover;
		this.accountNumber = accountNumber;
		this.accountType = accountType;
		this.currentBalance = currentBalance;
		this.createdDate = createdDate;
		this.approvalStatus = approvalStatus;
		this.interest = interest;
		this.approvalDate = approvalDate;
		this.transactionsForFromAccount = transactionsForFromAccount;
		this.transactionsForToAccount = transactionsForToAccount;
	}

	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	public User getUserByUserId() {
		return this.userByUserId;
	}

	public void setUserByUserId(User userByUserId) {
		this.userByUserId = userByUserId;
	}

	public User getUserByApprover() {
		return this.userByApprover;
	}

	public void setUserByApprover(User userByApprover) {
		this.userByApprover = userByApprover;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public BigDecimal getCurrentBalance() {
		return this.currentBalance;
	}

	public void setCurrentBalance(BigDecimal currentBalance) {
		this.currentBalance = currentBalance;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public boolean isApprovalStatus() {
		return this.approvalStatus;
	}

	public void setApprovalStatus(boolean approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	public BigDecimal getInterest() {
		return this.interest;
	}

	public void setInterest(BigDecimal interest) {
		this.interest = interest;
	}

	public Date getApprovalDate() {
		return this.approvalDate;
	}

	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}

	public Set getTransactionsForFromAccount() {
		return this.transactionsForFromAccount;
	}

	public void setTransactionsForFromAccount(Set transactionsForFromAccount) {
		this.transactionsForFromAccount = transactionsForFromAccount;
	}

	public Set getTransactionsForToAccount() {
		return this.transactionsForToAccount;
	}

	public void setTransactionsForToAccount(Set transactionsForToAccount) {
		this.transactionsForToAccount = transactionsForToAccount;
	}

}
