package com.example.hibernate;
// Generated Mar 13, 2020, 2:30:54 PM by Hibernate Tools 5.4.7.Final

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private AdminId id;

	public Admin() {
	}

	public Admin(AdminId id) {
		this.id = id;
	}

	public AdminId getId() {
		return this.id;
	}

	public void setId(AdminId id) {
		this.id = id;
	}

}
