package com.example.hibernate;
// Generated Mar 11, 2020, 5:05:15 PM by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * Appointment generated by hbm2java
 */
public class Appointment implements java.io.Serializable {

	private int appointmentId;
	private User userByAppointmentUserId;
	private User userByAssignedToUserId;
	private Date createdDate;
	private String appointmentStatus;

	public Appointment() {
	}

	public Appointment(int appointmentId, User userByAppointmentUserId, User userByAssignedToUserId, Date createdDate,
			String appointmentStatus) {
		this.appointmentId = appointmentId;
		this.userByAppointmentUserId = userByAppointmentUserId;
		this.userByAssignedToUserId = userByAssignedToUserId;
		this.createdDate = createdDate;
		this.appointmentStatus = appointmentStatus;
	}

	public int getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(int appointmentId) {
		this.appointmentId = appointmentId;
	}

	public User getUserByAppointmentUserId() {
		return this.userByAppointmentUserId;
	}

	public void setUserByAppointmentUserId(User userByAppointmentUserId) {
		this.userByAppointmentUserId = userByAppointmentUserId;
	}

	public User getUserByAssignedToUserId() {
		return this.userByAssignedToUserId;
	}

	public void setUserByAssignedToUserId(User userByAssignedToUserId) {
		this.userByAssignedToUserId = userByAssignedToUserId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getAppointmentStatus() {
		return this.appointmentStatus;
	}

	public void setAppointmentStatus(String appointmentStatus) {
		this.appointmentStatus = appointmentStatus;
	}

}
