package com.example.hibernate;
// Generated Mar 13, 2020, 2:30:54 PM by Hibernate Tools 5.4.7.Final

/**
 * CheckingAccount generated by hbm2java
 */
public class CheckingAccount implements java.io.Serializable {

	private CheckingAccountId id;

	public CheckingAccount() {
	}

	public CheckingAccount(CheckingAccountId id) {
		this.id = id;
	}

	public CheckingAccountId getId() {
		return this.id;
	}

	public void setId(CheckingAccountId id) {
		this.id = id;
	}

}
