package com.example.hibernate;
// Generated Mar 13, 2020, 2:30:54 PM by Hibernate Tools 5.4.7.Final

/**
 * ChequeTransaction generated by hbm2java
 */
public class ChequeTransaction implements java.io.Serializable {

	private ChequeTransactionId id;

	public ChequeTransaction() {
	}

	public ChequeTransaction(ChequeTransactionId id) {
		this.id = id;
	}

	public ChequeTransactionId getId() {
		return this.id;
	}

	public void setId(ChequeTransactionId id) {
		this.id = id;
	}

}
