package com.example.hibernate;
// Generated Mar 11, 2020, 5:51:53 PM by Hibernate Tools 5.4.7.Final

/**
 * CriticalTransaction generated by hbm2java
 */
public class CriticalTransaction implements java.io.Serializable {

	private CriticalTransactionId id;

	public CriticalTransaction() {
	}

	public CriticalTransaction(CriticalTransactionId id) {
		this.id = id;
	}

	public CriticalTransactionId getId() {
		return this.id;
	}

	public void setId(CriticalTransactionId id) {
		this.id = id;
	}

}
