package com.example.hibernate;
// Generated Mar 11, 2020, 5:19:25 PM by Hibernate Tools 5.4.7.Final

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private CustomerId id;

	public Customer() {
	}

	public Customer(CustomerId id) {
		this.id = id;
	}

	public CustomerId getId() {
		return this.id;
	}

	public void setId(CustomerId id) {
		this.id = id;
	}

}
