package com.example.hibernate;
// Generated Mar 13, 2020, 2:30:54 PM by Hibernate Tools 5.4.7.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * DebitTransactionId generated by hbm2java
 */
public class DebitTransactionId implements java.io.Serializable {

	private int transactionId;
	private String transactionType;
	private boolean approvalStatus;
	private BigDecimal amount;
	private boolean isCriticalTransaction;
	private Date requestedDate;
	private Date decisionDate;
	private int fromAccount;
	private int toAccount;
	private int approver;
	private Boolean level1Approval;
	private Boolean level2Approval;

	public DebitTransactionId() {
	}

	public DebitTransactionId(int transactionId, String transactionType, boolean approvalStatus,
			boolean isCriticalTransaction, Date requestedDate, Date decisionDate, int fromAccount, int toAccount,
			int approver) {
		this.transactionId = transactionId;
		this.transactionType = transactionType;
		this.approvalStatus = approvalStatus;
		this.isCriticalTransaction = isCriticalTransaction;
		this.requestedDate = requestedDate;
		this.decisionDate = decisionDate;
		this.fromAccount = fromAccount;
		this.toAccount = toAccount;
		this.approver = approver;
	}

	public DebitTransactionId(int transactionId, String transactionType, boolean approvalStatus, BigDecimal amount,
			boolean isCriticalTransaction, Date requestedDate, Date decisionDate, int fromAccount, int toAccount,
			int approver, Boolean level1Approval, Boolean level2Approval) {
		this.transactionId = transactionId;
		this.transactionType = transactionType;
		this.approvalStatus = approvalStatus;
		this.amount = amount;
		this.isCriticalTransaction = isCriticalTransaction;
		this.requestedDate = requestedDate;
		this.decisionDate = decisionDate;
		this.fromAccount = fromAccount;
		this.toAccount = toAccount;
		this.approver = approver;
		this.level1Approval = level1Approval;
		this.level2Approval = level2Approval;
	}

	public int getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public boolean isApprovalStatus() {
		return this.approvalStatus;
	}

	public void setApprovalStatus(boolean approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public boolean isIsCriticalTransaction() {
		return this.isCriticalTransaction;
	}

	public void setIsCriticalTransaction(boolean isCriticalTransaction) {
		this.isCriticalTransaction = isCriticalTransaction;
	}

	public Date getRequestedDate() {
		return this.requestedDate;
	}

	public void setRequestedDate(Date requestedDate) {
		this.requestedDate = requestedDate;
	}

	public Date getDecisionDate() {
		return this.decisionDate;
	}

	public void setDecisionDate(Date decisionDate) {
		this.decisionDate = decisionDate;
	}

	public int getFromAccount() {
		return this.fromAccount;
	}

	public void setFromAccount(int fromAccount) {
		this.fromAccount = fromAccount;
	}

	public int getToAccount() {
		return this.toAccount;
	}

	public void setToAccount(int toAccount) {
		this.toAccount = toAccount;
	}

	public int getApprover() {
		return this.approver;
	}

	public void setApprover(int approver) {
		this.approver = approver;
	}

	public Boolean getLevel1Approval() {
		return this.level1Approval;
	}

	public void setLevel1Approval(Boolean level1Approval) {
		this.level1Approval = level1Approval;
	}

	public Boolean getLevel2Approval() {
		return this.level2Approval;
	}

	public void setLevel2Approval(Boolean level2Approval) {
		this.level2Approval = level2Approval;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DebitTransactionId))
			return false;
		DebitTransactionId castOther = (DebitTransactionId) other;

		return (this.getTransactionId() == castOther.getTransactionId())
				&& ((this.getTransactionType() == castOther.getTransactionType())
						|| (this.getTransactionType() != null && castOther.getTransactionType() != null
								&& this.getTransactionType().equals(castOther.getTransactionType())))
				&& (this.isApprovalStatus() == castOther.isApprovalStatus())
				&& ((this.getAmount() == castOther.getAmount()) || (this.getAmount() != null
						&& castOther.getAmount() != null && this.getAmount().equals(castOther.getAmount())))
				&& (this.isIsCriticalTransaction() == castOther.isIsCriticalTransaction())
				&& ((this.getRequestedDate() == castOther.getRequestedDate())
						|| (this.getRequestedDate() != null && castOther.getRequestedDate() != null
								&& this.getRequestedDate().equals(castOther.getRequestedDate())))
				&& ((this.getDecisionDate() == castOther.getDecisionDate())
						|| (this.getDecisionDate() != null && castOther.getDecisionDate() != null
								&& this.getDecisionDate().equals(castOther.getDecisionDate())))
				&& (this.getFromAccount() == castOther.getFromAccount())
				&& (this.getToAccount() == castOther.getToAccount()) && (this.getApprover() == castOther.getApprover())
				&& ((this.getLevel1Approval() == castOther.getLevel1Approval())
						|| (this.getLevel1Approval() != null && castOther.getLevel1Approval() != null
								&& this.getLevel1Approval().equals(castOther.getLevel1Approval())))
				&& ((this.getLevel2Approval() == castOther.getLevel2Approval())
						|| (this.getLevel2Approval() != null && castOther.getLevel2Approval() != null
								&& this.getLevel2Approval().equals(castOther.getLevel2Approval())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTransactionId();
		result = 37 * result + (getTransactionType() == null ? 0 : this.getTransactionType().hashCode());
		result = 37 * result + (this.isApprovalStatus() ? 1 : 0);
		result = 37 * result + (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result + (this.isIsCriticalTransaction() ? 1 : 0);
		result = 37 * result + (getRequestedDate() == null ? 0 : this.getRequestedDate().hashCode());
		result = 37 * result + (getDecisionDate() == null ? 0 : this.getDecisionDate().hashCode());
		result = 37 * result + this.getFromAccount();
		result = 37 * result + this.getToAccount();
		result = 37 * result + this.getApprover();
		result = 37 * result + (getLevel1Approval() == null ? 0 : this.getLevel1Approval().hashCode());
		result = 37 * result + (getLevel2Approval() == null ? 0 : this.getLevel2Approval().hashCode());
		return result;
	}

}
