package com.example.hibernate;
// Generated Mar 11, 2020, 5:51:53 PM by Hibernate Tools 5.4.7.Final

/**
 * DebitTransaction generated by hbm2java
 */
public class DebitTransaction implements java.io.Serializable {

	private DebitTransactionId id;

	public DebitTransaction() {
	}

	public DebitTransaction(DebitTransactionId id) {
		this.id = id;
	}

	public DebitTransactionId getId() {
		return this.id;
	}

	public void setId(DebitTransactionId id) {
		this.id = id;
	}

}
