package com.example.hibernate;
// Generated Mar 11, 2020, 5:51:53 PM by Hibernate Tools 5.4.7.Final

/**
 * NonCriticalTransaction generated by hbm2java
 */
public class NonCriticalTransaction implements java.io.Serializable {

	private NonCriticalTransactionId id;

	public NonCriticalTransaction() {
	}

	public NonCriticalTransaction(NonCriticalTransactionId id) {
		this.id = id;
	}

	public NonCriticalTransactionId getId() {
		return this.id;
	}

	public void setId(NonCriticalTransactionId id) {
		this.id = id;
	}

}
