package com.example.hibernate;
// Generated Mar 13, 2020, 2:30:54 PM by Hibernate Tools 5.4.7.Final

/**
 * SavingsAccount generated by hbm2java
 */
public class SavingsAccount implements java.io.Serializable {

	private SavingsAccountId id;

	public SavingsAccount() {
	}

	public SavingsAccount(SavingsAccountId id) {
		this.id = id;
	}

	public SavingsAccountId getId() {
		return this.id;
	}

	public void setId(SavingsAccountId id) {
		this.id = id;
	}

}
