package com.example.hibernate;
// Generated Mar 13, 2020, 2:30:54 PM by Hibernate Tools 5.4.7.Final

/**
 * Tier2 generated by hbm2java
 */
public class Tier2 implements java.io.Serializable {

	private Tier2Id id;

	public Tier2() {
	}

	public Tier2(Tier2Id id) {
		this.id = id;
	}

	public Tier2Id getId() {
		return this.id;
	}

	public void setId(Tier2Id id) {
		this.id = id;
	}

}
