package com.example.hibernate;
// Generated Mar 13, 2020, 2:30:54 PM by Hibernate Tools 5.4.7.Final

/**
 * Tier1 generated by hbm2java
 */
public class Tier1 implements java.io.Serializable {

	private Tier1Id id;

	public Tier1() {
	}

	public Tier1(Tier1Id id) {
		this.id = id;
	}

	public Tier1Id getId() {
		return this.id;
	}

	public void setId(Tier1Id id) {
		this.id = id;
	}

}
