package com.example.hibernate;
// Generated Mar 13, 2020, 2:30:54 PM by Hibernate Tools 5.4.7.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

	private Integer transactionId;
	private Account accountByFromAccount;
	private Account accountByToAccount;
	private User user;
	private String transactionType;
	private boolean approvalStatus;
	private BigDecimal amount;
	private boolean isCriticalTransaction;
	private Date requestedDate;
	private Date decisionDate;
	private Boolean level1Approval;
	private Boolean level2Approval;

	public Transaction() {
	}

	public Transaction(Account accountByFromAccount, Account accountByToAccount, User user, String transactionType,
			boolean approvalStatus, boolean isCriticalTransaction, Date requestedDate, Date decisionDate) {
		this.accountByFromAccount = accountByFromAccount;
		this.accountByToAccount = accountByToAccount;
		this.user = user;
		this.transactionType = transactionType;
		this.approvalStatus = approvalStatus;
		this.isCriticalTransaction = isCriticalTransaction;
		this.requestedDate = requestedDate;
		this.decisionDate = decisionDate;
	}

	public Transaction(Account accountByFromAccount, Account accountByToAccount, User user, String transactionType,
			boolean approvalStatus, BigDecimal amount, boolean isCriticalTransaction, Date requestedDate,
			Date decisionDate, Boolean level1Approval, Boolean level2Approval) {
		this.accountByFromAccount = accountByFromAccount;
		this.accountByToAccount = accountByToAccount;
		this.user = user;
		this.transactionType = transactionType;
		this.approvalStatus = approvalStatus;
		this.amount = amount;
		this.isCriticalTransaction = isCriticalTransaction;
		this.requestedDate = requestedDate;
		this.decisionDate = decisionDate;
		this.level1Approval = level1Approval;
		this.level2Approval = level2Approval;
	}

	public Integer getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	public Account getAccountByFromAccount() {
		return this.accountByFromAccount;
	}

	public void setAccountByFromAccount(Account accountByFromAccount) {
		this.accountByFromAccount = accountByFromAccount;
	}

	public Account getAccountByToAccount() {
		return this.accountByToAccount;
	}

	public void setAccountByToAccount(Account accountByToAccount) {
		this.accountByToAccount = accountByToAccount;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public boolean isApprovalStatus() {
		return this.approvalStatus;
	}

	public void setApprovalStatus(boolean approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public boolean isIsCriticalTransaction() {
		return this.isCriticalTransaction;
	}

	public void setIsCriticalTransaction(boolean isCriticalTransaction) {
		this.isCriticalTransaction = isCriticalTransaction;
	}

	public Date getRequestedDate() {
		return this.requestedDate;
	}

	public void setRequestedDate(Date requestedDate) {
		this.requestedDate = requestedDate;
	}

	public Date getDecisionDate() {
		return this.decisionDate;
	}

	public void setDecisionDate(Date decisionDate) {
		this.decisionDate = decisionDate;
	}

	public Boolean getLevel1Approval() {
		return this.level1Approval;
	}

	public void setLevel1Approval(Boolean level1Approval) {
		this.level1Approval = level1Approval;
	}

	public Boolean getLevel2Approval() {
		return this.level2Approval;
	}

	public void setLevel2Approval(Boolean level2Approval) {
		this.level2Approval = level2Approval;
	}

}
