package com.example.hibernate;
// Generated Mar 13, 2020, 2:30:54 PM by Hibernate Tools 5.4.7.Final

/**
 * TransferTransaction generated by hbm2java
 */
public class TransferTransaction implements java.io.Serializable {

	private TransferTransactionId id;

	public TransferTransaction() {
	}

	public TransferTransaction(TransferTransactionId id) {
		this.id = id;
	}

	public TransferTransactionId getId() {
		return this.id;
	}

	public void setId(TransferTransactionId id) {
		this.id = id;
	}

}
