package com.example.hibernate;
// Generated Mar 13, 2020, 2:30:54 PM by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * UserDetailsId generated by hbm2java
 */
public class UserDetailsId implements java.io.Serializable {

	private int userId;
	private String firstName;
	private String middleName;
	private String lastName;
	private String email;
	private String phone;
	private String tier;
	private String address1;
	private String address2;
	private String city;
	private String province;
	private int zip;
	private Date dateOfBirth;
	private String ssn;
	private String question1;
	private String question2;

	public UserDetailsId() {
	}

	public UserDetailsId(int userId, String firstName, String lastName, String email, String phone, String address1,
			String address2, String city, String province, int zip, Date dateOfBirth, String ssn, String question1,
			String question2) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.province = province;
		this.zip = zip;
		this.dateOfBirth = dateOfBirth;
		this.ssn = ssn;
		this.question1 = question1;
		this.question2 = question2;
	}

	public UserDetailsId(int userId, String firstName, String middleName, String lastName, String email, String phone,
			String tier, String address1, String address2, String city, String province, int zip, Date dateOfBirth,
			String ssn, String question1, String question2) {
		this.userId = userId;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
		this.tier = tier;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.province = province;
		this.zip = zip;
		this.dateOfBirth = dateOfBirth;
		this.ssn = ssn;
		this.question1 = question1;
		this.question2 = question2;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getTier() {
		return this.tier;
	}

	public void setTier(String tier) {
		this.tier = tier;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public int getZip() {
		return this.zip;
	}

	public void setZip(int zip) {
		this.zip = zip;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	public String getQuestion1() {
		return this.question1;
	}

	public void setQuestion1(String question1) {
		this.question1 = question1;
	}

	public String getQuestion2() {
		return this.question2;
	}

	public void setQuestion2(String question2) {
		this.question2 = question2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserDetailsId))
			return false;
		UserDetailsId castOther = (UserDetailsId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getFirstName() == castOther.getFirstName()) || (this.getFirstName() != null
						&& castOther.getFirstName() != null && this.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getMiddleName() == castOther.getMiddleName()) || (this.getMiddleName() != null
						&& castOther.getMiddleName() != null && this.getMiddleName().equals(castOther.getMiddleName())))
				&& ((this.getLastName() == castOther.getLastName()) || (this.getLastName() != null
						&& castOther.getLastName() != null && this.getLastName().equals(castOther.getLastName())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getPhone() == castOther.getPhone()) || (this.getPhone() != null
						&& castOther.getPhone() != null && this.getPhone().equals(castOther.getPhone())))
				&& ((this.getTier() == castOther.getTier()) || (this.getTier() != null && castOther.getTier() != null
						&& this.getTier().equals(castOther.getTier())))
				&& ((this.getAddress1() == castOther.getAddress1()) || (this.getAddress1() != null
						&& castOther.getAddress1() != null && this.getAddress1().equals(castOther.getAddress1())))
				&& ((this.getAddress2() == castOther.getAddress2()) || (this.getAddress2() != null
						&& castOther.getAddress2() != null && this.getAddress2().equals(castOther.getAddress2())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& ((this.getProvince() == castOther.getProvince()) || (this.getProvince() != null
						&& castOther.getProvince() != null && this.getProvince().equals(castOther.getProvince())))
				&& (this.getZip() == castOther.getZip())
				&& ((this.getDateOfBirth() == castOther.getDateOfBirth())
						|| (this.getDateOfBirth() != null && castOther.getDateOfBirth() != null
								&& this.getDateOfBirth().equals(castOther.getDateOfBirth())))
				&& ((this.getSsn() == castOther.getSsn()) || (this.getSsn() != null && castOther.getSsn() != null
						&& this.getSsn().equals(castOther.getSsn())))
				&& ((this.getQuestion1() == castOther.getQuestion1()) || (this.getQuestion1() != null
						&& castOther.getQuestion1() != null && this.getQuestion1().equals(castOther.getQuestion1())))
				&& ((this.getQuestion2() == castOther.getQuestion2()) || (this.getQuestion2() != null
						&& castOther.getQuestion2() != null && this.getQuestion2().equals(castOther.getQuestion2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result + (getMiddleName() == null ? 0 : this.getMiddleName().hashCode());
		result = 37 * result + (getLastName() == null ? 0 : this.getLastName().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getPhone() == null ? 0 : this.getPhone().hashCode());
		result = 37 * result + (getTier() == null ? 0 : this.getTier().hashCode());
		result = 37 * result + (getAddress1() == null ? 0 : this.getAddress1().hashCode());
		result = 37 * result + (getAddress2() == null ? 0 : this.getAddress2().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getProvince() == null ? 0 : this.getProvince().hashCode());
		result = 37 * result + this.getZip();
		result = 37 * result + (getDateOfBirth() == null ? 0 : this.getDateOfBirth().hashCode());
		result = 37 * result + (getSsn() == null ? 0 : this.getSsn().hashCode());
		result = 37 * result + (getQuestion1() == null ? 0 : this.getQuestion1().hashCode());
		result = 37 * result + (getQuestion2() == null ? 0 : this.getQuestion2().hashCode());
		return result;
	}

}
